### ISSUE TITLE
Closing coinflip

### ISSUE THREAD

**Issue by IonicSyz1823** [KingOfTurkey38/CoinFlip#2]
No matter what you do when u tried to close the coinflip menu after selecting which player u wanna go with, the coinflip still spin. Even when u click the small x on top right of the gui the coinflip raffle still run

**Comment by KingOfTurkey38** [comment]
You can't close the menu anymore, if you do it will resend it. It will automaticly close it when the CoinFlip ended https://github.com/KingOfTurkey38/CoinFlip/commit/9778db911482caaf2f9bc26b605daea5dd5ae111
